name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- ÉTAPE AJOUTÉE : Configuration de Python ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # --- ÉTAPE AJOUTÉE : Installation et Tests ---
      - name: Install dependencies & Run Tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # On génère un rapport XML pour Sonar
          pytest --cov=. --cov-report=xml:coverage.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4 # Vérifiez la version la plus récente
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml