name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Installation des outils de tests
          pip install pytest pytest-cov selenium webdriver-manager
          # Installation des dépendances de l'application
          if [ -f application/requirement.txt ]; then pip install -r application/requirement.txt; fi
          # Installation forcée des librairies spécifiques citées (au cas où elles manquent dans le requirement.txt)
          pip install streamlit pandas openpyxl psycopg2-binary sqlalchemy

      - name: Run tests with coverage
        run: |
          # On lance les tests du dossier /tests 
          # On mesure la couverture sur le dossier /application
          # --cov=application génère les stats pour votre code source
          pytest tests/ --cov=application --cov-report=xml:coverage.xml --junitxml=test-results.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.xunit.reportPath=test-results.xml